version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: banking-ledger-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/banking-ledger
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - JWT_REFRESH_SECRET=dev-refresh-secret-change-in-production
      - PORT=3000
      - LOG_LEVEL=debug
    depends_on:
      - mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:6
    container_name: banking-ledger-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=banking-ledger
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/banking-ledger --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-setup:
    image: mongo:6
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./docker/mongodb/setup.sh:/setup.sh:ro
    entrypoint: ["/bin/bash", "/setup.sh"]

  mongo-express:
    image: mongo-express:latest
    container_name: banking-ledger-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: